name: GuildPlugin
version: 1.2.4
main: com.guild.GuildPlugin
api-version: '1.21'
authors: [chenasyd]
description: Um plugin de guilda completo para Minecraft, suportando Spigot e Folia
website: https://github.com/chenasyd
softdepend: [PlaceholderAPI, Vault]

# Versão mínima suportada
load: POSTWORLD

# Marca de suporte Folia
folia-supported: true

commands:
  guild:
    description: Comando principal do sistema de guilda
    usage: /guild help
    aliases: [g, guilda]
    permission: guild.use
  guildadmin:
    description: Comando de administrador de guilda
    usage: /guildadmin help
    aliases: [ga, guildaadmin]
    permission: guild.admin

permissions:
  guild.use:
    description: Permite usar o sistema de guilda
    default: true
  guild.admin:
    description: Permissão de administrador de guilda
    default: op
  guild.create:
    description: Permite criar guilda
    default: true
  guild.invite:
    description: Permite convidar jogadores para a guilda
    default: true
  guild.kick:
    description: Permite expulsar membros da guilda
    default: true
  guild.promote:
    description: Permite promover membros da guilda
    default: true
  guild.demote:
    description: Permite rebaixar membros da guilda
    default: true
  guild.delete:
    description: Permite deletar guilda
    default: op
  guild.sethome:
    description: Permite definir home da guilda
    default: true
  guild.home:
    description: Permite teleportar para home da guilda
    default: true
  guild.relation:
    description: Permite gerenciar relações da guilda
    default: true
  guild.economy:
    description: Permite gerenciar economia da guilda
    default: true
  guild.deposit:
    description: Permite depositar fundos na guilda
    default: true
  guild.withdraw:
    description: Permite sacar fundos da guilda
    default: true
  guild.transfer:
    description: Permite transferir para outras guildas
    default: true
