# Arquivo de configuração do banco de dados

# Tipo de banco de dados: mysql ou sqlite
type: sqlite

# Configuração MySQL (usado quando type é mysql)
mysql:
  # Endereço do host do banco de dados
  host: localhost
  # Porta do banco de dados
  port: 3306
  # Nome do banco de dados
  database: guild
  # Nome de usuário do banco de dados
  username: root
  # Senha do banco de dados
  password: ""
  # Tamanho do pool de conexões
  pool-size: 10
  # Mínimo de conexões ociosas
  min-idle: 5
  # Tempo limite de conexão (milissegundos)
  connection-timeout: 30000
  # Tempo limite de ociosidade (milissegundos)
  idle-timeout: 600000
  # Tempo de vida máximo da conexão (milissegundos)
  max-lifetime: 1800000
  # Se usa SSL
  use-ssl: false
  # Codificação de caracteres
  character-encoding: UTF-8
  # Fuso horário
  timezone: UTC

# Configuração SQLite (usado quando type é sqlite)
sqlite:
  # Caminho do arquivo do banco de dados (relativo à pasta de dados do plugin)
  file: guild.db
  # Se ativa modo WAL
  wal-mode: true
  # Modo de sincronização: OFF, NORMAL, FULL
  synchronous: NORMAL
  # Tamanho do cache (KB)
  cache-size: 2000
  # Tamanho da página (bytes)
  page-size: 4096
  # Se ativa restrições de chave estrangeira
  foreign-keys: true

# Configuração do pool de conexões
connection-pool:
  # Máximo de conexões
  maximum-pool-size: 10
  # Mínimo de conexões ociosas
  minimum-idle: 5
  # Tempo limite de conexão (milissegundos)
  connection-timeout: 30000
  # Tempo limite de ociosidade (milissegundos)
  idle-timeout: 600000
  # Tempo de vida máximo da conexão (milissegundos)
  max-lifetime: 1800000
  # Consulta de teste de conexão
  connection-test-query: "SELECT 1"
  # Tempo limite de validação (milissegundos)
  validation-timeout: 5000
  # Se valida conexão ao iniciar pool
  validate-on-start: true

# Configuração de tabelas do banco de dados
tables:
  # Tabela de guildas
  guilds:
    name: guilds
    # Se cria tabela automaticamente
    auto-create: true
    # Versão da estrutura da tabela
    version: 1
  
  # Tabela de membros da guilda
  guild_members:
    name: guild_members
    auto-create: true
    version: 1
  
  # Tabela de aplicações da guilda
  guild_applications:
    name: guild_applications
    auto-create: true
    version: 1
  
  # Tabela de convites da guilda
  guild_invites:
    name: guild_invites
    auto-create: true
    version: 1

# Configuração de backup
backup:
  # Se ativa backup automático
  enabled: false
